### ISSUE TITLE
As an organizer I want to be able to register a new event so that I can manage the new conference

### ISSUE THREAD

**Issue by JoaoVilhena00** [FEUP-ESOF-2020-21/open-cx-t6g4-the-five-engineers#10]
Each **event** will have:
* Name
* Short description
* Tags (Stuff like `tech` `android` `c++` `portuguese` `english-friendly`)
* Session list

Each **session** will have: 
* Start date
* Finish date
* Location (can be remote, mixed, etc.)
* Attendance limit

### Acceptance Tests
* Name size <= 50 chars
* Start date and finish date of each session must be valid dates
* Start date of each session must be before or same as the finish date
* Start date of each session must be same or after conference start date
* Finish date of each session must be same or before conference finish date
* Maximum of 100 sessions (may change later)
* Maximum of 50 tags
* Tag size <= 50 chars
* Attendance limit, if it exists, must be a positive number
* Short description size <= 1000 chars

### To-Do
- [x] Model
  - [x] Initial class structure
    - [x] Conference
    - [x] Event
    - [x] Session
- [x] View
  - [x] Create Event 
    - [x] Initial structure
    - [x] Implement session `ListView`
  - [x] Create Session
  - [x] Error checking on attributes

**Comment by GoncaloPascoal** [comment]
**Note:** `TextField` isn't currently enforcing the `maxLength` property, even when `maxLengthEnforced` is true. We may need to find a workaround for limiting the number of characters in a field. [Relevant issue on Flutter's GitHub page](https://github.com/flutter/flutter/issues/67898)
