### ISSUE TITLE
Firebase Connection

### ISSUE THREAD

**Issue by biam05** [FEUP-ESOF-2020-21/open-cx-t6g4-the-five-engineers#28]
### To-Do List
- [x] Update required dependencies
- [x] Initialize Firebase when app starts
- [x] Conference
  - [x] Add conference to database when it is created successfully
  - [x] Test Firebase integration
- [x] Event
  - [x] Add event to database when it is created succesfully
  - [x] Test Firebase integration
  - [x] Redo `createEvent` function after the view conference screen is added
- [x] View conference screen
  - [x] Fetch conference information from database
- [x] View event screen
  - [x] Fetch event information from database
- [x] Select conference (organizer)
  - [x] Save user uid when creating a conference
  - [x] Only select the conferences that match the uid of the logged in user.
