### ISSUE TITLE
Modify session creation to have a start time and duration

### ISSUE THREAD

**Issue by GoncaloPascoal** [FEUP-ESOF-2020-21/open-cx-t6g4-the-five-engineers#35]
### Motivation
A start time and duration is more intuitive for the user (we can still show them the end date) for defining a session. This also makes some acceptance tests easier to pass and reduces the chance of invalid values.

### To-Do
- [x] Search for a number picker widget in https://pub.dev
- [x] Add number picker widget to dependencies
- [x] Replace end date picker with number picker widget for hours and minutes
- [x] Define a maximum session duration
- [x] Add a text box that updates whenever the user picks a new duration and make it show the resulting end date
